### ISSUE TITLE
Visit Sörmland - öppna data

### ISSUE THREAD

**Issue by salgo60** [dpriskorn/svenska-vandringsleder#22]
**Försöka få [Öppna data](https://internetstiftelsen.se/kunskap/for-samhallet/oppna-data/) från Visit Sörmland**

* [Planeringsverktyg
Genom Visit Sörmlands planeringsverktyg får du en överblick av Sörmlandsledens etapper. Här kan du enkelt planera din vandring och boka boende samt aktiviteter när du ändå ska ut på tur.](https://visitsormland.se/vandra/planera-din-vandring/)

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/14206509/200157652-cefb16c0-db97-4ad3-973a-8630f7f1fcf0.png">

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/14206509/200157694-9c7dc774-bdf9-4cf4-ae56-db1b0f2fb4a7.png">

![image](https://user-images.githubusercontent.com/14206509/200161044-0bfa32f8-4229-4722-b15b-4a786480c3b1.png)

**Planeringskartan har ett antal intressanta kategorier**
<img width="406" alt="image" src="https://user-images.githubusercontent.com/14206509/200161378-af024e3a-f611-4c36-a063-4aa7a817a1a0.png">
<img width="406" alt="image" src="https://user-images.githubusercontent.com/14206509/200161400-e222b15b-06eb-42cc-85c6-230d6e7359c9.png">

**Exempel vatten**

![image](https://user-images.githubusercontent.com/14206509/200161353-6ac5e7fb-7350-4c6e-bbd1-8c474a1ddee0.png)

**Comment by salgo60** [comment]
**Metadata på etapper i Wikidata** [SPARQL](https://w.wiki/5v54)

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/14206509/200161621-c2a9708c-2dc1-46e4-814c-608e23c354b2.png">

**Comment by salgo60** [comment]
**Status efter 12 dagar:** Inget svar

**Comment by dpriskorn** [comment]
Snyggt planeringsverktyg och datamodell. 
Tyvärr verkar det vara ännu en silo. 🤷‍♂️
Det finns minst 500 vandringsleder och politikerna pratar om turism och bla bla men faktum är att vi är otroligt långt från att jag som koreansk vandringsturist kan få bra data om vilken led som helst enkelt via EN app på koreanska med en maskinöversatt beskrivning. 

Wikidata och wikibase möjliggör detta men intresset verkar vara icke-existerande i dagsläget och alla lösningar vi ser byggs i silos utan helhetstänk eller språktänk. 🤷‍♂️

**Comment by salgo60** [comment]
@dpriskorn tror denna resan med öppen källkod och linked data är längre än man kan inse....

* @jonor pekade på att NOSAD inte levererar metadata och verkar helt ointresserade... gissar att dom inte fattar möjligheten...
  * jonass tror jag har rätt kompetens men tycker Maria vill väl men snurrar in sig i massa DIGG dumheter och lägger tid på att flytta [runt inlägg och skapa länkröta](https://community.dataportal.se/topic/590/tillg%C3%A5ng-nekad-brutna-l%C3%A4nkar-eller-st%C3%A4ngda-tr%C3%A5dar) - hennes roll behövs men hon [skall **inte** fundera om dataset är bra definierade eller hur metadatat skall se ut](https://community.dataportal.se/topic/576/hur-du-f%C3%A5r-tillg%C3%A5ng-till-%C3%B6ppna-data-om-laddstationer/31?_=1668951206888)

**Comment by salgo60** [comment]
Stänger denna ingen feedback
